class ExpenseCategories {
  static const List<String> categories = [
    'Income',
    'Food & Dining',
    'Groceries',
    'Shopping',
    'Transport & Fuel',
    'Bills & Utilities',
    'Investments',
    'Loans & Debt',
    'Healthcare',
    'Entertainment',
    'Personal Transfers',
    'Self Transfer',
    'General Expenses',
    'Not Applicable / Exclude',
  ];

  static const Map<String, List<String>> defaultSubCategories = {
    'Self Transfer': [
      'Account to Account Transfer',
      'Self UPI Transfer',
      'Savings to Investment',
      'Credit Card Bill Payment',
      'Wallet Top-up',
    ],
    'Loans & Debt': [
      'Personal Loan EMI',
      'Home Loan EMI',
      'Car Loan EMI',
      'Education Loan EMI',
      'Consumer Loan EMI',
      'General Loan EMI',
    ],
    'Income': [
      'Salary',
      'Bonus & Incentives',
      'Freelance & Consulting',
      'Reimbursements',
      'Dividends & Interest',
      'Rental Income',
      'Refunds',
    ],
    'Food & Dining': [
      'Tea & Snacks',
      'Restaurants & Cafes',
      'Coffee & Bakeries',
      'Street Food',
      'Online Delivery (Swiggy/Zomato)',
      'Fast Food & Takeaway',
      'Bar & Pub',
    ],
    'Groceries': [
      'Supermarket',
      'Fruits & Vegetables',
      'Dairy & Eggs',
      'Local Kirana Store',
      'Meat & Seafood',
    ],
    'Transport & Fuel': [
      'Fuel & Petrol',
      'Cabs & Rides (Uber/Ola)',
      'Metro & Rail',
      'Bus & Transit',
      'FASTag & Tolls',
      'Parking',
      'Auto & Bike Repair',
    ],
    'Shopping': [
      'Clothing & Apparel',
      'Electronics & Gadgets',
      'Home & Kitchen',
      'Online Shopping (Amazon/Flipkart)',
      'Personal Care & Cosmetics',
      'Books & Stationery',
    ],
    'Bills & Utilities': [
      'Credit Card Bill',
      'Electricity Bill',
      'Mobile Recharge & Postpaid',
      'Broadband / Wi-Fi',
      'Water Bill',
      'House Rent',
      'Maid & Cook Wages',
      'LPG Cylinder',
      'Society Maintenance',
    ],
    'Investments': [
      'Recurring Deposit (RD)',
      'Mutual Funds & SIP',
      'Stocks & Demat',
      'Fixed Deposit',
      'Gold & Silver',
      'Provident Fund / NPS',
      'Crypto',
    ],
    'Healthcare': [
      'Doctor & Clinic Visit',
      'Medicines & Pharmacy',
      'Lab Diagnostics & Scans',
      'Health Insurance',
      'Dental & Optical',
    ],
    'Entertainment': [
      'Movies & Theatres',
      'Streaming OTT (Netflix/Prime)',
      'Music & Gaming',
      'Events & Concerts',
      'Hobbies & Outings',
    ],
    'Personal Transfers': [
      'Friends & Family',
      'Domestic Staff',
      'Rent Transfer',
      'Reimbursements',
      'Loans Repaid/Given',
    ],
    'General Expenses': [
      'Miscellaneous',
      'Cash Withdrawal (ATM)',
      'Bank Charges & Fees',
      'Charity & Donations',
    ],
  };
}
